version: 2

jobs:
  build:
    docker:
      - image: hashicorp/terraform:light
    working_directory: /terraform
    steps:
      - checkout
      - run:
          name: install make
          command: apk add -U make
      - run:
          name: terraform init
          command: >
            terraform init -input=false
            terraform get
      - run:
          name: Validate Terraform configurations
          command: make validate
      - run:
          name: Check if Terraform configurations are properly formatted
          command: make check-format
      - run:
          name: Install tflint
          command: curl -L -o /tmp/tflint.zip https://github.com/wata727/tflint/releases/download/v0.4.2/tflint_linux_amd64.zip && unzip /tmp/tflint.zip -d /usr/local/bin
      - run:
          name: Check Terraform configurations with tflint
          command: tflint

