version: 2

jobs:
  build:
    docker:
      - image: hashicorp/terraform:light
    working_directory: /terraform
    environment:
      AWS_REGION: ap-southeast-1

    steps:
      - checkout
      - run:
          name: install make
          command: apk add -U make
      - run:
          name: Validate Terraform configurations
          command: make -s validate
      - run:
          name: Check if Terraform configurations are properly formatted
          command: make -s check-format
